language: c

# select container based VM (no sudo available)
sudo: false

# use gcc as the C compiler
compiler: gcc

# specify operating systems to test on (linux and/or osx)
os:
  - linux

# environment variables for the build
env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=5.1.3
    - LUA=5.1.4
    - LUA=5.1.5
    - LUA=5.2.2
    - LUA=5.2.3
    - LUA=5.2.4
    - LUA=5.3.0
    - LUA=5.3.1
    - LUA=5.3.2
    - LUA=5.3.3
    - LUA=5.3.4

# only test changes to the master branch
branches:
  only:
    - master

# disable email notifications
notifications:
  email: false

# install dependencies (lua, luarocks, ...)
install:
  - . .travis/install.sh

# build (and test?) the project
script:
  - luarocks make CFLAGS="-Wall -Wextra -O2 -fPIC" && lua tests/test.lua

